### PR TITLE
Private Events | Logic

### PR DESCRIPTION
**Pull request by uzairali19**
This branch will consist of all the development for the app's private events. In this app, the user can create an event. Many users can attend the assigned event and the event belongs to the owner.

### CODE REVIEW

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: :stop_sign: 
---------------------
Hello @uzairali19, great job you are doing on this project :muscle: :clap: 
TO HIGHLIGHT: 

- Your repo is professional 
- Well structured files 
- Well use of the MVP

However, there are a few changes to make to complete this project :wrench: see them below :point_down: 
---------------

- [x] Please Add a descriptive Readme file. 
- [ ] I got this error when I trying to `rails s `. Even if I run `rails webpacker:install`

Screenshot from 2021-08-23 18-15-58

Please fix this

- [x] It has creation date as attribute. 

event_date_requirement

- [x] Scope for upcoming and previous events. 

scopes_requirement

- `scope :upcoming, -> { where('date >= ?', Time.zone.now) }`
- `scope :previous, -> { where('date < ?', Time.zone.now) }`

* [x] Lists past events, i.e. `@past_events = Event.previous_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png))
* [x] Lists upcoming events, i.e. `@upcoming_events = Event.upcoming_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png))

- [x] Lists events created by user, i.e. `@created_events = current_user.events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) )
* [x] Lists events previoulsy attendented by user **using event model scope**, i.e. `@past_events = current_user.attended_events.previous` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png))
* [x] Lists upcoming events previously attended by user **using event model scope**, i.e. `@upcoming_events = current_user.attended_events.upcoming` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) )

-------------------
Please make these required changes and send it again for another review :-1: :100: 
HAPPY CODING!!!

**Comment by uzairali19** [comment]
> ## CHANGES REQUIRED 🔴 🛑
> Hello @uzairali19, great job you are doing on this project 💪 👏
> TO HIGHLIGHT:
> 
> * Your repo is professional
> * Well structured files
> * Well use of the MVP
> 
> ## However, there are a few changes to make to complete this project 🔧 see them below 👇
> * [x]  Please Add a descriptive Readme file.
> * [ ]  I got this error when I trying to `rails s `. Even if I run `rails webpacker:install`
> 
> Screenshot from 2021-08-23 18-15-58
> 
> Please fix this
> 
> * [x]  It has creation date as attribute.
> 
> event_date_requirement
> 
> * [x]  Scope for upcoming and previous events.
> 
> scopes_requirement
> 
> * `scope :upcoming, -> { where('date >= ?', Time.zone.now) }`
> * `scope :previous, -> { where('date < ?', Time.zone.now) }`
> 
> * [x]  Lists past events, i.e. `@past_events = Event.previous_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png))
> * [x]  Lists upcoming events, i.e. `@upcoming_events = Event.upcoming_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png))
> 
> * [x]  Lists events created by user, i.e. `@created_events = current_user.events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) )
> 
> * [x]  Lists events previoulsy attendented by user **using event model scope**, i.e. `@past_events = current_user.attended_events.previous` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png))
> * [x]  Lists upcoming events previously attended by user **using event model scope**, i.e. `@upcoming_events = current_user.attended_events.upcoming` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) )
> 
> Please make these required changes and send it again for another review 👎 💯
> HAPPY CODING!!!
> 

Hello Brain,

Thank you for such a  brief comment. I have made the necessary changes to my project. ie. `upcoming_events` and `previous_events`

- I would like to quote that if you are unable to run the application, please try removing the `Gemfile.lock` and run `bundle install` in the root directory. As you can see the error states that you need to update webpacker dependencies, if in case that does not work, please check the application.js files under `public/packs/js` are populated properly.

- Secondly, my events have a creation date attribute. You may want to double-check that. I am attaching a screenshot for your better understanding. However, you can also look at my migrations and schema to confirm the field exists.
screenshot


Thanks
Uzair Ali

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: 
---------------
Hello there again :wave:, Great job working on the required changes :clap: 
There are some changes to make :hammer_and_wrench: see them below :point_down: 
---------------------

- [x] I cannot log out. When I click on the log out button it redirects to `show user`. Please fix this. 

Screenshot from 2021-08-24 10-22-31

- [x] I got an error when I trying to attend an event. 

Screenshot from 2021-08-24 10-31-43

- [x] On your step about how to clone the repo you must create the database `rails db:create` before migrate the database. Please add the command that is missing. 

------------

NOTE: For the error trying to run the app, the solution you provided does not work. I just delete the line that is getting conflicts  ` <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>` 

Make these required changes and send it again for another review :muscle: 
SLACK: Brian Sammit Cruz Rodriguez
HAPPY CODING!!!

**Comment by uzairali19** [comment]
> * rails db:create

Hey Brain,

Thank you for testing my app. 

You are a developer yourself, if you delete `<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>` how can you logout a user session or add an attendee since they use javascript to make data available in frontend.

I think the problem is where you are setting up the app itself. For your easiness I have uploaded the packs folder in my drive attaching the link below. Please download it and locate it under the `public` folder. The app on my end is running perfectly.
However I have added `rails db:create` in readme file. Thanks for that.

Here is the link:
`https://drive.google.com/drive/folders/1JOCRjb-NsM4E7NREZ3TaQrmkGHTdnxrZ?usp=sharing`

Please approve my project now. The app is running perfectly on my end. You have to have the javascript tag to workout on the frontend to store data. If you delete that you will get the errors you mentioned. Furthermore, If you still find any difficulties testing the app I would recommend you to test my app through `rails console`. My relationships should be perfect as per the requirements. Please let me know if you run into any other problems.

Thanks
Uzair Ali

**Review by BrianSammit — APPROVED** [review]
STATUS: APPROVED :green_circle: 
---------------
Hello there, Good job working on this project your app is working properly :100: 
-----------
Now you can merge this branch :+1: :100: 
HAPPY CODING!!!

**Pull request merged**
